# Generated by Django 5.1.7 on 2025-03-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
