# Generated by Django 5.1.7 on 2025-03-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0002_alter_apoyo_nombre_alter_apoyo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='tipo',
            field=models.CharField(choices=[('alimentario', 'Alimentario'), ('económico', 'Económico'), ('vivienda', 'Vivienda')], max_length=50),
        ),
    ]
