# Generated by Django 5.1.7 on 2025-03-27 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0004_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoyo',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Apoyo', 'verbose_name_plural': 'Apoyos'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='apoyo',
            name='descripcion_corta',
            field=models.TextField(default='Descripción breve', max_length=50),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='apoyos'),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción completa'),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del apoyo'),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='tipo',
            field=models.CharField(choices=[('alimentario', 'Alimentario'), ('económico', 'Económico'), ('vivienda', 'Vivienda')], max_length=50, verbose_name='Tipo de apoyo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='apoyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyos.apoyo', verbose_name='Apoyo solicitado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
