# Generated by Django 5.1.7 on 2025-03-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0005_alter_apoyo_options_alter_solicitud_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyo',
            name='descripcion_corta',
            field=models.TextField(default='Descripción breve', max_length=150),
        ),
    ]
