# Generated by Django 5.1.7 on 2025-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0006_alter_apoyo_descripcion_corta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyo',
            name='descripcion_corta',
            field=models.TextField(default='Descripción breve', max_length=250),
        ),
    ]
