# Generated by Django 5.1.7 on 2025-03-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0007_alter_apoyo_descripcion_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoyo',
            name='disponible',
            field=models.BooleanField(choices=[(True, 'Disponible'), (False, 'No disponible')], default=True, verbose_name='Disponibilidad'),
        ),
    ]
