# Generated by Django 5.1.7 on 2025-03-31 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0008_apoyo_disponible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoyo',
            options={},
        ),
    ]
