# Generated by Django 5.1.7 on 2025-03-31 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0009_alter_apoyo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoyo',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Apoyo', 'verbose_name_plural': 'Apoyos'},
        ),
    ]
