# Generated by Django 5.1.7 on 2025-04-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0010_alter_apoyo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoyo',
            name='imagen',
        ),
    ]
