# Generated by Django 5.1.7 on 2025-04-01 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0011_remove_apoyo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del requisito')),
                ('apoyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='apoyos.apoyo', verbose_name='Apoyo')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
    ]
