# Generated by Django 5.1.7 on 2025-04-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0012_requisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisito',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
