# Generated by Django 5.1.7 on 2025-04-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0014_pregunta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyo',
            name='descripcion_corta',
            field=models.TextField(max_length=250),
        ),
    ]
