# Generated by Django 5.1.7 on 2025-04-15 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0015_alter_apoyo_descripcion_corta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de apoyo')),
            ],
            options={
                'verbose_name': 'Tipo de Apoyo',
                'verbose_name_plural': 'Tipos de Apoyo',
            },
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyos.tipoapoyo', verbose_name='Tipo de apoyo'),
        ),
    ]
