# Generated by Django 5.1.7 on 2025-04-17 21:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0017_solicitud_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_requisitos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyos.requisito')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='apoyos.solicitud')),
            ],
        ),
    ]
