# Generated by Django 5.1.7 on 2025-04-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0018_documentorequisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='condiciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='educacion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nivel educativo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mayor_edad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='situacion',
            field=models.TextField(blank=True, verbose_name='Situación actual'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='vivienda',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de vivienda'),
        ),
    ]
