# Generated by Django 5.1.7 on 2025-04-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0019_solicitud_condiciones_solicitud_educacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
    ]
