# Generated by Django 5.1.7 on 2025-04-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0020_solicitud_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentorequisito',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='documentorequisito',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
