# Generated by Django 5.1.7 on 2025-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0023_apoyo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyo',
            name='descripcion_corta',
            field=models.TextField(max_length=400),
        ),
    ]
