# Generated by Django 5.1.7 on 2025-04-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0024_alter_apoyo_descripcion_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoyo',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
