# Generated by Django 5.1.7 on 2025-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0025_apoyo_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='clave_elector',
            field=models.CharField(blank=True, max_length=18, verbose_name='Clave de Elector'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='seccion',
            field=models.CharField(blank=True, max_length=5, verbose_name='Sección Electoral'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='vigencia',
            field=models.CharField(blank=True, max_length=4, verbose_name='Vigencia de INE'),
        ),
    ]
