# Generated by Django 5.1.7 on 2025-04-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='curp',
            field=models.CharField(default=1, max_length=18, unique=True, verbose_name='CURP'),
            preserve_default=False,
        ),
    ]
