# Generated by Django 5.1.7 on 2025-04-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_customuser_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='curp',
            field=models.CharField(default='TEMP000000XXXXXX00', max_length=18, unique=True, verbose_name='CURP'),
        ),
    ]
