# Generated by Django 5.1.7 on 2025-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_customuser_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('administrador', 'Administrador'), ('alcalde', 'Alcalde (Superadmin)')], default='usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='curp',
            field=models.CharField(max_length=18, unique=True, verbose_name='CURP'),
        ),
    ]
