# Generated by Django 5.1.7 on 2025-04-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_customuser_rol_alter_customuser_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
    ]
