# Generated by Django 5.1.7 on 2025-04-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_customuser_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
    ]
