# Generated by Django 5.1.7 on 2025-04-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_municipiocp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipiocp',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
    ]
