# Generated by Django 5.1.7 on 2025-04-08 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_alter_municipiocp_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codigo_postal',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d+$', 'Este campo solo acepta números.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='curp',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{18}$', 'La CURP debe contener 18 caracteres en mayúsculas y números.')], verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Este campo solo acepta números.')]),
        ),
    ]
