# Generated by Django 5.1.7 on 2025-04-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0008_alter_customuser_codigo_postal_alter_customuser_curp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipiocp',
            options={'verbose_name': 'Municipio con CP', 'verbose_name_plural': 'Municipios con CP'},
        ),
    ]
