# Generated by Django 5.1.7 on 2025-04-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0009_alter_municipiocp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipiocp',
            options={},
        ),
    ]
