# Generated by Django 5.1.7 on 2025-04-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0011_alter_municipiocp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipiocp',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='curp',
            field=models.CharField(max_length=18, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
