# Generated by Django 5.1.7 on 2025-04-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0012_alter_municipiocp_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
